# Generated by Django 3.0.4 on 2020-03-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(default='null', max_length=50)),
                ('description', models.TextField()),
                ('featured', models.BooleanField()),
                ('date_created', models.DateField()),
                ('date_removed', models.DateField()),
            ],
        ),
    ]
