# Generated by Django 3.0.4 on 2020-04-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0004_auto_20200408_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
