# Generated by Django 3.0.4 on 2020-04-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0008_auto_20200408_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
