# Generated by Django 3.0.4 on 2020-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateField(auto_now=True),
        ),
    ]
