# Generated by Django 3.0.4 on 2020-04-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0013_auto_20200412_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
