# Generated by Django 3.0.4 on 2020-04-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0014_remove_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amenity.Cart')),
                ('product', models.CharField(max_length=100)),
            ],
            bases=('amenity.cart',),
        ),
    ]
