# Generated by Django 3.0.4 on 2020-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0016_cart_products_in_cart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_in_cart_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
