# Generated by Django 3.0.4 on 2020-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0018_auto_20200415_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
