# Generated by Django 3.0.4 on 2020-05-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0019_auto_20200418_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amenity.Cart')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amenity.Product')),
            ],
        ),
    ]
